# Generated by Django 5.1.1 on 2024-10-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Cumpleaños'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número telefónico'),
        ),
    ]
